(function(scope){
  const particles={Delta:'Дельта',Epsilon:'Эпсилон',Zeta:'Дзета',Sigma:'Сигма'};
  function advise(state,roles,severity=''){
    if(severity!==''&&(!Number.isFinite(Number(severity))||Number(severity)<0||Number(severity)>100))return 'Опасность должна быть числом от 0 до 100%.';
    if(state==='critical'||severity!==''&&Number(severity)>=100)return 'Сверхкритическое состояние: прекратите обычное исследование, отведите людей и сообщите отделу об угрозе. Обычная схема стабилизации не отменяет уже запущенное событие. Проверьте последствия этого типа аномалии ниже.';
    const known=Object.values(roles).filter(Boolean);
    if(known.some(v=>!particles[v])||new Set(known).size!==known.length)return 'Проверьте показания: один тип частицы не может одновременно иметь две роли. Пересканируйте аномалию.';
    if(state==='unknown')return 'Сначала считайте текущее состояние сканером. По одному типу или внешнему виду аномалии нельзя выбрать нужную частицу.';
    if(state==='stable')return 'Состояние стабильно: не стреляйте без цели. Следите за опасностью и таймером импульса; после импульса или изменения поведения повторите сканирование. Стабильная аномалия всё ещё создаёт эффекты.';
    const role=state==='growing'?'containment':'unstable';
    if(!roles[role])return `Для этого состояния нужно знать ${role==='containment'?'сдерживающий':'нестабильный'} тип. Если сканер скрывает его, универсального безопасного выбора нет. Уточните показания и поведение, не подставляйте случайную букву.`;
    if(state==='growing')return `Для сдерживания роста выберите «${particles[roles.containment]}» — сдерживающий тип по введённым показаниям. Воздействуйте малыми порциями и пересканируйте. Сдерживание снижает показатель стабильности и скрытое здоровье, но не уменьшает опасность напрямую. Избыток погасит аномалию; число выстрелов заранее не гарантируется.`;
    return `Если цель — сохранить распадающуюся аномалию, «${particles[roles.unstable]}» является нестабильным типом по введённым показаниям и повышает показатель стабильности. После малого воздействия пересканируйте: избыток переведёт аномалию в рост. Если цель — завершить исследование, не поддерживайте её.`;
  }
  scope.AnomalyDesk={advise};if(!scope.document||!scope.ANOMALY_DATA)return;
  const data=scope.ANOMALY_DATA,$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const root=$('scientist'),artifacts=document.createElement('div');artifacts.id='science-artifacts';while(root.firstChild)artifacts.append(root.firstChild);root.append(artifacts);
  const nav=document.createElement('div');nav.className='science-tabs science-topics';nav.setAttribute('role','group');nav.setAttribute('aria-label','Разделы учёного');nav.innerHTML='<button data-science-topic="artifacts" aria-pressed="true" aria-controls="science-artifacts">Артефакты</button><button data-science-topic="anomalies" aria-pressed="false" aria-controls="science-anomalies">Аномалии</button>';root.prepend(nav);
  const section=document.createElement('section');section.id='science-anomalies';section.hidden=true;section.setAttribute('aria-labelledby','anomaly-title');root.append(section);
  section.innerHTML=`<header class="science-hero"><div><span class="science-eyebrow">НАУЧНЫЙ ОТДЕЛ / АНОМАЛИСТИКА</span><h2 id="anomaly-title">Исследовать и удержать</h2><p>Что показывает сканер, какими частицами воздействовать и чего ждать от импульса.</p></div><div class="science-stats"><span><b>${data.anomalies.length}</b> вариантов</span><span><b>${data.behaviors.length}</b> поведение</span></div></header>
  <details class="science-guide" open><summary>Начать исследование · от поиска до очков</summary><div class="science-guide-grid"><article><h3>1. Найдите и подготовьте</h3><ol><li>Найдите аномалию локатором или по сообщению о появлении. Генератор на плазме создаёт её в случайном месте, а не обязательно рядом с собой.</li><li>Освободите путь отхода, ограничьте доступ и подготовьте защиту под конкретный тип из справочника ниже.</li><li>Просканируйте аномалию анализатором аномалий. Запишите опасность, состояние, таймер и роли четырёх частиц.</li></ol></article><article><h3>2. Подключите и контролируйте</h3><ol><li>Примените сканер с записанной аномалией к свободному сосуду. Одна аномалия не привязывается к нескольким сосудам одновременно.</li><li>Проверьте питание сосуда и исследовательскую сеть. Сосуд собирает очки, но не делает саму аномалию безопасной.</li><li>Для воздействия используйте доступный излучатель частиц: стационарный М.А.К.А.К. или ручное устройство с нужным режимом. Настройте тип по свежему сканированию.</li><li>После каждого небольшого воздействия проверяйте состояние. Не оставляйте растущую аномалию под непрерывным обстрелом.</li></ol></article><article><h3>3. Завершите работу</h3><ul><li>При распаде падает скрытое здоровье. Сдерживающий тип также снижает здоровье и может погасить аномалию.</li><li>При 100% опасности запускается сверхкритическое событие. Прекратите обычный опыт, отведите людей и предупредите отдел.</li><li>После распада обычно остаётся инертное ядро; после сверхкритического события — обычное ядро соответствующего типа. Не устраивайте катастрофу ради ядра.</li><li>Проверьте место после исчезновения: огонь, существа, реагенты и повреждения могут остаться.</li></ul></article></div></details>
  <div class="science-meaning"><p><b>Опасность</b> определяет силу последствий. 100% запускает сверхкритическое событие; высокие очки не означают безопасное состояние.</p><p><b>Состояние</b> — распад, стабильность или рост. Базово: показатель стабильности ниже 15% — распад, выше 50% — рост. Рост увеличивает опасность при импульсах.</p></div>
  <details class="science-guide"><summary>Частицы: четыре буквы, четыре случайные роли</summary><div class="anomaly-roles"><article><h3>Опасный тип</h3><p>Повышает опасность. Базовое изменение +2,5 процентного пункта за попадание, до модификаторов и случайного разброса.</p></article><article><h3>Нестабильный тип</h3><p>Повышает показатель стабильности. Базово +4 п.п. Помогает выйти из распада, но избыток приводит к росту.</p></article><article><h3>Сдерживающий тип</h3><p>Базово −10 п.п. стабильности и −5 п.п. скрытого здоровья. Не является прямым снижением опасности.</p></article><article><h3>Трансформирующий тип</h3><p>Повышает опасность и с вероятностью, зависящей от непрерывности, меняет поведение. Не гарантирует превращение огненной аномалии в другой вид.</p></article></div><p class="science-source">Роли дельты, эпсилона, дзеты и сигмы назначаются случайно. Чувствительность поведения и разброс ×0,8–1,2 меняют результат попадания. При непостоянстве роли могут перемешиваться.</p></details>
  <details class="science-guide"><summary>Помощник по показаниям сканера</summary><form id="anomaly-helper" class="anomaly-helper"><p>Перенесите свежие показания. Это памятка по введённым данным, без связи с игрой и без расчёта гарантированного числа выстрелов.</p><div class="anomaly-helper-grid"><label>Состояние<select name="state"><option value="unknown">Неизвестно</option><option value="growing">Рост</option><option value="stable">Стабильно</option><option value="decaying">Распад</option><option value="critical">Сверхкритическое</option></select></label><label>Опасность, %<input name="severity" type="number" min="0" max="100" step="any" placeholder="Неизвестно"></label>${[['danger','Опасный тип'],['unstable','Нестабильный тип'],['containment','Сдерживающий тип'],['transform','Трансформирующий тип']].map(([key,label])=>`<label>${label}<select name="${key}"><option value="">Неизвестно / скрыто</option>${Object.entries(particles).map(([k,n])=>`<option value="${k}">${n}</option>`).join('')}</select></label>`).join('')}</div><p id="anomaly-advice" class="anomaly-advice" role="status"></p><button type="reset" class="quiet">Очистить показания</button></form></details>
  <div class="science-tabs" role="group" aria-label="Каталог аномалий"><button data-anomaly-mode="anomalies" aria-pressed="true">Виды и последствия</button><button data-anomaly-mode="behaviors" aria-pressed="false">Отклонения поведения</button></div><div class="science-controls"><label class="science-search"><span>Найти тип или фразу сканера</span><input id="anomaly-search" type="search" placeholder="Гравитация, непостоянство, плазма…"></label></div><div class="science-meta"><span id="anomaly-count" role="status"></span><button id="anomaly-reset" class="quiet">Сбросить поиск</button></div><div id="anomaly-results" class="science-results"></div><p class="science-source">Данные локальной сборки: ${data.generated}. Пояснения основаны на прототипах и Content.Shared/Anomaly, Content.Server/Anomaly. Здесь перечислены обычные пространственные типы из anomalies.yml, включая подарочный; внутренние инъекции аномалий — отдельная механика. Название вида не определяет поведение: оно может скрывать данные, менять роли частиц или перемещать аномалию.</p>`;
  section.querySelector('.science-guide').insertAdjacentHTML('afterend',`<details class="science-guide"><summary>Оборудование, ядра и сигналы</summary><div class="science-guide-grid"><article><h3>Измерения и воздействие</h3><p class="science-source">Локатор помогает найти аномалию; сканер показывает состояние и роли частиц. Излучатель воздействует выбранной частицей. Эти инструменты не заменяют друг друга. Ошибка сканера может быть свойством поведения, а не поломкой.</p></article><article><h3>Сосуды</h3><p class="science-source">Обычный сосуд собирает очки с привязанной аномалии. Экспериментальный имеет множитель очков ×2 и источник радиации интенсивностью 0,75 при подключении. Размещайте рабочие места с учётом излучения. Привязка сосуда не переносит аномалию внутрь машины.</p></article><article><h3>Синхронизатор и ядра</h3><p class="science-source">Синхронизатор переводит импульсы и изменения аномалии в сигналы для подключённых устройств. Это инструмент автоматизации, а не автоматическая стабилизация. Ядро остаётся после завершения аномалии и имеет собственные свойства; инертное и обычное ядра не взаимозаменяемы во всех устройствах.</p></article></div></details>`);
  let mode='anomalies';
  function render(){const words=$('anomaly-search').value.toLowerCase().replaceAll('ё','е').trim().split(/\s+/).filter(Boolean);const list=data[mode].filter(v=>words.every(w=>JSON.stringify(v).toLowerCase().replaceAll('ё','е').includes(w)));$('anomaly-count').textContent=`Найдено: ${list.length} / ${data[mode].length}`;$('anomaly-results').innerHTML=list.map(v=>`<details class="science-card" data-anomaly-id="${v.id}"><summary><span class="science-kind">${mode==='anomalies'?'Вид аномалии':'Поведение · '+v.id}</span><span class="science-name">${esc(v.name)}</span><span class="science-preview">${esc(v.effect||v.details[0])}</span><span class="science-more">Подробнее <b>＋</b></span></summary><div class="science-card-body">${mode==='anomalies'?`<h4>Обычное воздействие</h4><p>${esc(v.effect)}</p><h4>Сверхкритическое событие</h4><p class="science-callout">${esc(v.critical)}</p><h4>Как подготовиться</h4><p>${esc(v.advice)}</p>`:`<ul>${v.details.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><p class="science-source">Множитель интервала больше 1 означает более редкие импульсы, меньше 1 — более частые. Одна фраза сканера может соответствовать нескольким вариантам поведения.</p>`}<details class="source"><summary>Источник и параметры</summary><code>${esc(v.source)} · ${v.id}</code><pre>${esc(JSON.stringify(v.components||v.raw,null,2))}</pre></details></div></details>`).join('')||'<p class="science-empty">Совпадений нет. Попробуйте другое слово или сбросьте поиск.</p>';}
  nav.addEventListener('click',e=>{const b=e.target.closest('[data-science-topic]');if(!b)return;artifacts.hidden=b.dataset.scienceTopic!=='artifacts';section.hidden=!artifacts.hidden;nav.querySelectorAll('button').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));});
  section.addEventListener('click',e=>{const b=e.target.closest('[data-anomaly-mode]');if(!b)return;mode=b.dataset.anomalyMode;section.querySelectorAll('[data-anomaly-mode]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));render();});
  $('anomaly-search').addEventListener('input',render);$('anomaly-reset').addEventListener('click',()=>{$('anomaly-search').value='';render();});
  const form=$('anomaly-helper');function update(){const f=form.elements;$('anomaly-advice').textContent=advise(f.state.value,{danger:f.danger.value,unstable:f.unstable.value,containment:f.containment.value,transform:f.transform.value},f.severity.value);}
  form.addEventListener('input',update);form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('reset',()=>queueMicrotask(update));update();render();
})(typeof module==='object'&&module.exports?module.exports:window);
