'use strict';
(() => {
  const valid=n=>Number.isFinite(n)&&n>=0;
  function value(rows,mixed=false){if(!rows.every(r=>valid(r.amount)&&valid(r.price)))return null;const total=rows.reduce((s,r)=>s+r.amount,0),base=rows.reduce((s,r)=>s+r.amount*r.price,0),purity=mixed&&total?Math.max(...rows.map(r=>r.amount))/total:1;return {total,base,purity,value:base*purity};}
  function duration(start,end,seconds,target,setup=0){if(![start,end,target,setup].every(valid)||!Number.isFinite(seconds)||seconds<=0)return null;const rate=(end-start)/seconds;return {rate,seconds:end>=target?setup:rate>0?setup+(target-end)/rate:null};}
  const plans={
    tritium:{name:'Тритий из плазмы',product:'Tritium',input:{Plasma:1,Oxygen:96},output:{Tritium:1,Oxygen:95.6},note:'Идеальный баланс при T ≥1643,15 K и O₂/плазма ≥96. Учтён возвращаемый избыток кислорода. Вторичное сгорание трития и потери не учтены.'},
    frezon:{name:'Фрезон',product:'Frezon',input:{Oxygen:50/51,Tritium:1/51,Nitrogen:5/51},output:{Frezon:1,Nitrogen:5/51},note:'Идеальный баланс при 73,15 K: O₂:тритий =50:1, азот возвращается как катализатор. Конкурирующая реакция охлаждения расходует продукт, поэтому реальный выход нужно уточнить по замеру.'},
    coolant:{name:'N₂O из фрезона',product:'NitrousOxide',input:{Frezon:1/6,Nitrogen:5/6},output:{NitrousOxide:1},note:'Баланс 1 фрезона +5 азота →6 N₂O при достаточном количестве обоих газов. По мере охлаждения скорость падает.'},
    ammonia:{name:'N₂O из аммиака',product:'NitrousOxide',input:{Ammonia:2,Oxygen:2},output:{NitrousOxide:1,WaterVapor:3},note:'Баланс 2 NH₃ +2 O₂ →1 N₂O +3 пара. От 323,149 K; при 850 K и выше начинается разложение N₂O.'},
    steam:{name:'Пар из трития',product:'WaterVapor',input:{Tritium:1,Oxygen:1},output:{WaterVapor:1,Oxygen:.5},note:'Вход 1:1, расход кислорода 0,5 кПа на 1 кПа трития при одинаковых опорных условиях; остаток кислорода включён в выход. Усиленная ветка дополнительно требует достаточной тепловой энергии.'},
    decomposition:{name:'Кислород из N₂O',product:'Oxygen',input:{NitrousOxide:2},output:{Oxygen:1,Nitrogen:2},note:'Термическое разложение от 850 K: 2 N₂O →2 N₂ +1 O₂. Это не газовый переработчик.'}
  };
  function batch(id,amount){const plan=plans[id];if(!plan||!Number.isFinite(amount)||amount<=0)return null;return {...plan,input:Object.fromEntries(Object.entries(plan.input).map(([g,n])=>[g,n*amount])),output:Object.fromEntries(Object.entries(plan.output).map(([g,n])=>[g,n*amount]))};}
  const api={value,duration,batch,plans};if(typeof module!=='undefined')module.exports=api;if(typeof window==='undefined')return;window.AtmosEconomy=api;
  const d=window.ENGINEERING_DATA,host=document.getElementById('atmos-economy');if(!host||!d)return;
  const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(n);
  host.innerHTML=`<form id="atmos-economy-form" class="atmos-panel"><h3>Стоимость входа и выхода</h3><p class="science-source">Все количества — парциальные давления при температуре и объёме, заданных ниже, одинаковых для входа и выхода. Цены по умолчанию пересчитаны из игровой оценки на 1 кПа. Это не закупочный прайс: замените цену входа на свои затраты. Нулевая цена в прототипе не означает отсутствие расходов на производство. Укажите полный состав входной и выходной партии, включая примеси.</p><div class="atmos-table-wrap"><table class="atmos-table"><thead><tr><th>Газ</th><th>Вход, кПа</th><th>Цена входа / кПа</th><th>Выход, кПа</th><th>Цена выхода / кПа</th></tr></thead><tbody>${d.gases.map(g=>`<tr><th>${g.name}</th>${[['in',0],['buy',g.pricePerMole*1000/(d.constants.R*293.15)],['out',0],['sell',g.pricePerMole*1000/(d.constants.R*293.15)]].map(([key,v])=>`<td><input aria-label="${g.name}: ${key==='in'?'вход в кПа':key==='out'?'выход в кПа':key==='buy'?'цена входа':'цена выхода'}" name="${key}-${g.id}" type="number" min="0" step="any" value="${v}" required></td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="anomaly-helper-grid"><label>Учёт входа<select name="inputMode"><option value="separate">Сумма затрат / отдельные газы</option><option value="mixed">Игровая оценка одной смеси</option></select></label><label>Продажа выхода<select name="outputMode"><option value="separate">Каждый газ отделён в чистый</option><option value="mixed">Всё в одной смешанной канистре</option></select></label><label>Прочие затраты на партию<input name="overhead" type="number" min="0" step="any" value="0" required></label></div><div class="botany-buttons"><button type="button" id="economy-from-mix" class="secondary">Взять вход из калькулятора смеси</button><button type="reset" class="quiet">Сбросить количества и цены</button></div><div id="economy-result" role="status"></div><p class="science-source">Оценка смеси = Σ(кПа × цена) × наибольшая доля давления. Режим «отдельные газы» предполагает полное разделение без потерь. Стоимость самой канистры, торговые коэффициенты и незаписанные расходы здесь не учитываются. Источник: AtmosphereSystem.Utils.cs → GetPrice.</p></form>
  <form id="atmos-time-form" class="atmos-panel"><h3>Сколько осталось производить</h3><p class="science-source">Замерьте прирост давления чистого продукта в приёмнике при постоянных температуре и объёме (тех же, что указаны для партии выше). Нагрев без поступления газа не является производством. Фиксированного времени для рецепта нет: скорость зависит от подачи, температуры, запасов и отбора. Получится оценка по текущей производительности.</p><div class="anomaly-helper-grid"><label>Продукт<select name="product">${d.gases.map(g=>`<option value="${g.id}" ${g.id==='Frezon'?'selected':''}>${g.name}</option>`).join('')}</select></label><label>В начале замера, кПа<input name="start" type="number" min="0" step="any" placeholder="Например, 0" required></label><label>В конце замера, кПа<input name="end" type="number" min="0" step="any" placeholder="Например, 20" required></label><label>Между замерами, с<input name="seconds" type="number" min="0.001" step="any" value="60" required></label><label>Нужно накопить всего, кПа<input name="target" type="number" min="0" step="any" value="200" required></label><label>Дополнительная пауза / подготовка, с<input name="setup" type="number" min="0" step="any" value="0" required></label></div><button type="button" id="time-from-output" class="secondary">Взять цель из выхода партии</button><p id="time-result" role="status"></p><p class="science-source">Не откачивайте продукт из приёмника во время замера. При изменении режима сделайте новый замер. Нулевая или отрицательная скорость не даёт конечного времени завершения.</p></form>`;
  const f=$('atmos-economy-form'),t=$('atmos-time-form');
  const thumbnail=window.AtmosThumbnail||(()=> '');
  f.querySelector('.atmos-table-wrap').insertAdjacentHTML('beforebegin','<div class="anomaly-helper-grid"><label>Температура учёта партии, K<input name="basisT" type="number" min="0.001" step="any" value="293.15" required></label><label>Объём учёта партии, л<input name="basisV" type="number" min="0.001" step="any" value="1000" required></label></div><p class="science-source">При изменении температуры или объёма давления остаются заданными: это другая партия. Стандартные цены пересчитываются; введённые вручную цены за кПа сохраняются.</p>');
  const customPrices=new Set();
  f.addEventListener('input',e=>{if(/^(buy|sell)-/.test(e.target.name||''))customPrices.add(e.target.name);if(e.target.name==='basisT'||e.target.name==='basisV'){const t=number(f,'basisT'),v=number(f,'basisV');for(const g of d.gases)for(const prefix of ['buy','sell'])if(!customPrices.has(prefix+'-'+g.id))f.elements.namedItem(prefix+'-'+g.id).value=t>0&&v>0?g.pricePerMole*v/(d.constants.R*t):'';}});
  f.addEventListener('reset',()=>customPrices.clear());
  f.querySelectorAll('tbody tr>th').forEach((cell,i)=>cell.insertAdjacentHTML('afterbegin',thumbnail(d.gases[i].id)+' '));
  f.querySelector('h3').insertAdjacentHTML('afterbegin',thumbnail('economy')+' ');
  t.querySelector('h3').insertAdjacentHTML('afterbegin',thumbnail('equipment-0')+' ');
  f.querySelector('.atmos-table-wrap').insertAdjacentHTML('beforebegin',`<div class="anomaly-helper-grid"><label>Теоретический рецепт<select id="economy-plan">${Object.entries(plans).map(([id,p])=>`<option value="${id}" ${id==='frezon'?'selected':''}>${p.name}</option>`).join('')}</select></label><label>Нужный выход основного продукта, кПа<input id="economy-yield" type="number" min="0.001" step="any" value="200"></label></div><button type="button" id="economy-fill-plan" class="secondary">Рассчитать вход и выход партии</button><p id="economy-plan-note" class="science-callout">Можно заполнить количества по теоретическому балансу, затем исправить на фактические. Цены сохранятся.</p>`);
  function number(form,key){const s=form.elements.namedItem(key).value;return s.trim()===''?NaN:Number(s);}
  function update(){const input=value(d.gases.map(g=>({amount:number(f,'in-'+g.id),price:number(f,'buy-'+g.id)})),f.elements.inputMode.value==='mixed'),output=value(d.gases.map(g=>({amount:number(f,'out-'+g.id),price:number(f,'sell-'+g.id)})),f.elements.outputMode.value==='mixed'),extra=number(f,'overhead');$('economy-result').textContent=input&&output&&valid(extra)&&number(f,'basisT')>0&&number(f,'basisV')>0?`Вход: ${fmt(input.value)} · выход: ${fmt(output.value)} · прочие затраты: ${fmt(extra)} · разница: ${fmt(output.value-input.value-extra)}. Коэффициент чистоты выхода: ${fmt(output.purity*100)}%.`:'Заполните все количества и цены неотрицательными числами.';}
  function updateTime(){const r=duration(...['start','end','seconds','target','setup'].map(k=>number(t,k)));$('time-result').textContent=!r||!(number(f,'basisT')>0&&number(f,'basisV')>0)?'Введите показания, положительный интервал, температуру и объём учёта.':`Производительность: ${fmt(r.rate)} кПа/с. ${r.seconds==null?'Продукт не накапливается — срок не определён.':`Осталось примерно ${fmt(r.seconds)} с (${fmt(r.seconds/60)} мин), включая указанную паузу.`}`;}
  f.addEventListener('input',e=>{if(e.target.name==='basisT'||e.target.name==='basisV'){t.elements.start.value='';t.elements.end.value='';updateTime();}});
  f.addEventListener('input',update);f.addEventListener('reset',()=>queueMicrotask(()=>{update();$('economy-plan-note').textContent='Количества и цены сброшены.';}));t.addEventListener('input',e=>{if(e.target===t.elements.product){t.elements.start.value='';t.elements.end.value='';}updateTime();});[f,t].forEach(form=>form.addEventListener('submit',e=>e.preventDefault()));
  $('economy-fill-plan').addEventListener('click',()=>{const amount=Number($('economy-yield').value),p=batch($('economy-plan').value,amount);if(!p){$('economy-plan-note').textContent='Введите положительный выход продукта.';return;}for(const g of d.gases){f.elements.namedItem('in-'+g.id).value=p.input[g.id]||0;f.elements.namedItem('out-'+g.id).value=p.output[g.id]||0;}$('economy-plan-note').textContent=p.note;t.elements.product.value=p.product;t.elements.target.value=amount;t.elements.start.value='';t.elements.end.value='';update();updateTime();});
  $('economy-from-mix').addEventListener('click',()=>{const result=window.AtmosDesk.currentMix();if(!result||!(number(f,'basisT')>0&&number(f,'basisV')>0)){$('economy-result').textContent='Сначала задайте корректные давление, температуру и объём в калькуляторе смесей.';return;}for(const g of d.gases)f.elements.namedItem('in-'+g.id).value=(result.rows.find(r=>r.gas===g.id)?.moles||0)*d.constants.R*number(f,'basisT')/number(f,'basisV');$('economy-plan-note').textContent='Вход приведён к температуре и объёму учёта партии. Количества выхода оставлены как были — проверьте их для новой партии.';update();});
  $('time-from-output').addEventListener('click',()=>{t.elements.target.value=f.elements.namedItem('out-'+t.elements.product.value).value;updateTime();});update();updateTime();
})();
