window.MEDICAL_DATA = {
  "checked": "02.10.2026",
  "medicines": [
    {
      "id": "Bicaridine",
      "name": "Бикаридин",
      "level": "base",
      "group": "Механические",
      "treats": "Ушибы, порезы и уколы.",
      "overdose": 15,
      "harm": "Удушье, токсины и дрожь; от 30 ед. возможна рвота.",
      "note": "Может вызывать опьянение и без передозировки.",
      "color": "#ffaa00",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Dermaline",
      "name": "Дермалин",
      "level": "base",
      "group": "Ожоги",
      "treats": "Термические, электрические и холодовые повреждения.",
      "overdose": 10,
      "harm": "Удушье, холодовой и ушибный урон, дрожь.",
      "note": "Не лечит кислотный урон.",
      "color": "#215263",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Dylovene",
      "name": "Диловен",
      "level": "base",
      "group": "Токсины",
      "treats": "Токсический урон.",
      "overdose": 20,
      "harm": "Ушибный урон, дрожь, тошнота и возможная рвота.",
      "note": "Опьянение начинается уже от 15 ед. Лечение урона не означает удаление самого яда.",
      "color": "#3a1d8a",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Dexalin",
      "name": "Дексалин",
      "level": "base",
      "group": "Кислород / кровь",
      "treats": "Удушье и урон от кровопотери.",
      "overdose": 20,
      "harm": "Дополнительное удушье и холодовой урон.",
      "note": "Не восполняет объём крови и не закрывает кровотечение.",
      "color": "#0041a8",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Inaprovaline",
      "name": "Инапровалин",
      "level": "base",
      "group": "Критическое состояние",
      "treats": "Удушье в критическом состоянии; уменьшает кровотечение.",
      "overdose": null,
      "harm": "",
      "note": "Лечение удушья работает только в крите. Не устраняет остальные причины крита.",
      "color": "#731024",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Epinephrine",
      "name": "Эпинефрин",
      "level": "base",
      "group": "Критическое состояние",
      "treats": "В крите лечит удушье, токсины, механические повреждения и ожоги.",
      "overdose": 20,
      "harm": "Удушье и токсический урон.",
      "note": "Лечебные эффекты крита требуют не более 20 ед.; на самом пороге уже действует и вред. Уменьшает оглушение и замедление от ран.",
      "color": "#d2fffa",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Saline",
      "name": "Физраствор",
      "level": "base",
      "group": "Кислород / кровь",
      "treats": "Восполняет объём крови и утоляет жажду.",
      "overdose": null,
      "harm": "",
      "note": "Кровотечение нужно остановить отдельно.",
      "color": "#0064C8",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "TranexamicAcid",
      "name": "Транексамовая кислота",
      "level": "base",
      "group": "Кислород / кровь",
      "treats": "Снижает кровотечение.",
      "overdose": 15,
      "harm": "Наносит урон от кровопотери, хотя продолжает снижать кровотечение.",
      "note": "Не заменяет восполнение потерянной крови.",
      "color": "#ba7d7d",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Tricordrazine",
      "name": "Трикордразин",
      "level": "base",
      "group": "Комплексное",
      "treats": "Механические повреждения, ожоги и токсический урон вне крита.",
      "overdose": null,
      "harm": "",
      "note": "Не лечит в критическом состоянии: в прототипе требуется состояние Alive.",
      "color": "#00e5ff",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Hyronalin",
      "name": "Хироналин",
      "level": "base",
      "group": "Радиация",
      "treats": "Радиационный урон.",
      "overdose": 30,
      "harm": "Термический урон и дрожь.",
      "note": "Рвота возможна и без передозировки. Сначала уйдите от источника радиации.",
      "color": "#4cb580",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Bruizine",
      "name": "Бруизин",
      "level": "advanced",
      "group": "Механические",
      "treats": "Прицельно лечит ушибы.",
      "overdose": 10.5,
      "harm": "Токсический урон.",
      "note": "Для порезов и уколов нужны другие препараты.",
      "color": "#ff3636",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Lacerinol",
      "name": "Лацеринол",
      "level": "advanced",
      "group": "Механические",
      "treats": "Прицельно лечит порезы.",
      "overdose": 12,
      "harm": "Холодовой урон.",
      "note": "Не заменяет остановку кровотечения.",
      "color": "#283332",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Puncturase",
      "name": "Пунктураз",
      "level": "advanced",
      "group": "Механические",
      "treats": "Прицельно лечит уколы и проникающие повреждения.",
      "overdose": 12,
      "harm": "Дополнительный ушибный урон.",
      "note": "Небольшой ушибный урон наносится даже без передозировки.",
      "color": "#b9bf93",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Pyrazine",
      "name": "Пиразин",
      "level": "advanced",
      "group": "Ожоги",
      "treats": "Термические повреждения.",
      "overdose": 15,
      "harm": "От 15 ед. возможна рвота; от 20 ед. — режущий и колющий урон, крики.",
      "note": "Первый нежелательный эффект начинается раньше повреждений.",
      "color": "#aa4308",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Insuzine",
      "name": "Инсузин",
      "level": "advanced",
      "group": "Ожоги",
      "treats": "Электрические повреждения; выводит ликоксид и тазинид.",
      "overdose": 12,
      "harm": "Холодовой урон, сильное охлаждение и дрожь.",
      "note": "Понижает температуру и без передозировки.",
      "color": "#8147ff",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Leporazine",
      "name": "Лепоразин",
      "level": "advanced",
      "group": "Ожоги",
      "treats": "Холодовой урон; корректирует температуру тела и выводит фрезиум.",
      "overdose": null,
      "harm": "",
      "note": "Нагревает при температуре до 293,15 K и охлаждает от 293,15 K. Может мешать холодному лечению в крио.",
      "color": "#ff7db5",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Sigynate",
      "name": "Сигинат",
      "level": "advanced",
      "group": "Ожоги",
      "treats": "Кислотные повреждения.",
      "overdose": 16,
      "harm": "Термический урон; от 20 ед. дрожь и тошнота, от 30 ед. возможна рвота.",
      "note": "При наличии аритразина от 1 ед. возможны тошнота и рвота.",
      "color": "#e0a5b9",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "DexalinPlus",
      "name": "Дексалин плюс",
      "level": "advanced",
      "group": "Кислород / кровь",
      "treats": "Удушье и урон от кровопотери; выводит токсин разбитого сердца.",
      "overdose": 25,
      "harm": "Дополнительное удушье и холодовой урон.",
      "note": "Не восполняет объём крови и не останавливает кровотечение.",
      "color": "#4da0bd",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Diphenhydramine",
      "name": "Дифенгидрамин",
      "level": "advanced",
      "group": "Токсины",
      "treats": "Токсический урон; выводит гистамин и снимает дрожь.",
      "overdose": null,
      "harm": "",
      "note": "Вызывает сонливость. Не является универсальным средством для удаления всех ядов.",
      "color": "#64ffe6",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Arithrazine",
      "name": "Аритразин",
      "level": "advanced",
      "group": "Радиация",
      "treats": "Радиационный урон.",
      "overdose": null,
      "harm": "",
      "note": "Наносит ушибный урон при обычном действии.",
      "color": "#bd5902",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Cryoxadone",
      "name": "Криоксадон",
      "level": "advanced",
      "group": "Крио",
      "treats": "Механические повреждения, ожоги, токсинную группу и недостаток воздуха.",
      "overdose": null,
      "harm": "",
      "note": "Работает при температуре тела не выше 213 K (−60,15 °C). При комнатной температуре не лечит.",
      "color": "#0091ff",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Doxarubixadone",
      "name": "Доксарубиксадон",
      "level": "advanced",
      "group": "Крио",
      "treats": "Клеточный урон.",
      "overdose": null,
      "harm": "",
      "note": "Работает при температуре тела не выше 213 K (−60,15 °C).",
      "color": "#32cd32",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Omnizine",
      "name": "Омнизин",
      "level": "advanced",
      "group": "Комплексное",
      "treats": "Механические повреждения, ожоги, токсинную группу и недостаток воздуха.",
      "overdose": null,
      "harm": "",
      "note": "Не лечит клеточный урон. Получение зависит от доступных источников, в том числе ботаники.",
      "color": "#fcf7f9",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    },
    {
      "id": "Phalanximine",
      "name": "Фалангимин",
      "level": "advanced",
      "group": "Клеточный урон",
      "treats": "Лечит клеточный урон без охлаждения в крио.",
      "overdose": 11,
      "harm": "Дополнительный радиационный урон.",
      "note": "Даже без передозировки наносит небольшой радиационный и кислотный урон. За цикл: −0,6 клеточного, +0,15 радиационного и +0,15 кислотного урона. От 11 ед. добавляется ещё +0,2 радиационного.",
      "color": "#c8ff75",
      "source": "Resources/Prototypes/Reagents/medicine.yml"
    }
  ]
};
