(()=>{
  const data=window.SCIENTIST_DATA;if(!data)return;
  const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let mode='triggers';
  $('scientist').innerHTML=`<header class="science-hero"><div><span class="science-eyebrow">НАУЧНЫЙ ОТДЕЛ / КСЕНОАРХЕОЛОГИЯ</span><h2 id="scientist-title">Разобраться с артефактом</h2><p>Найдите фразу с анализатора — узнайте, что сделать и чего ждать.</p></div><div class="science-stats"><span><b>${data.triggers.length}</b> стимулов</span><span><b>${data.effects.length}</b> эффектов</span></div></header>
  <div class="science-meaning"><p><b>Стимул</b> — условие, которое нужно выполнить для узла: газ, реагент, инструмент или событие.</p><p><b>Реакция / эффект</b> — результат активации. Один стимул не определяет эффект: их сочетание зависит от узла.</p></div>
  <details class="science-guide"><summary>Как исследовать: порядок действий и частые ошибки</summary><div class="science-guide-grid"><article><h3>Порядок работы</h3><ol><li>Поместите артефакт на анализатор, подключите аналитическую консоль мультитулом и изучите дерево узлов.</li><li>Выберите доступный узел. Подготовьте стимулы самого узла и его предшественников по связям дерева.</li><li>Выполните нужные воздействия в пределах окна разблокировки. Не запускайте все инструменты и газы подряд: лишний сработавший узел может сорвать попытку.</li><li>Дождитесь результата. При успешном раскрытии эффект срабатывает — поэтому подготовьте испытательную камеру заранее.</li><li>Проверьте новые связи, ресурс узла и очки на консоли. Сканер узлов помогает следить за состоянием артефакта рядом с ним.</li></ol></article><article><h3>Если не срабатывает</h3><ul><li>После попытки есть пауза: базово 5 секунд. Базовое окно — 6 секунд, подходящие дополнительные стимулы могут продлить его на 10 секунд.</li><li>Проверьте, доступен ли узел по дереву и не подавлен ли артефакт контейнером.</li><li>Газ и температуру проверяют на клетке артефакта. Газ в закрытом баллоне рядом не равен нужной атмосфере.</li><li>Для реагента нужен контакт; малая порция может не достичь порога. Несколько альтернатив в карточке не нужно применять одновременно.</li><li>Не путайте стимул «магнитные волны» и эффект притяжения; бросать нужно сам ручной артефакт.</li></ul></article><article><h3>Что ещё полезно знать</h3><ul><li>Прочность узла — ресурс ручных активаций после раскрытия. У некоторых эффектов узел одноразовый, а полученное свойство остаётся у артефакта.</li><li>Артифексиум допускает один недостающий узел при подборе набора стимулов. Он не означает автоматического раскрытия всего дерева.</li><li>В этой сборке SS220 есть отдельная награда за полное раскрытие артефакта — в отличие от устаревшей фразы в общем руководстве.</li><li>Дробитель даёт фрагменты; четыре фрагмента собираются в новый артефакт через крафт.</li></ul></article></div><p class="science-source">Основания: Guidebook/Science/Xenoarchaeology.xml; SharedXenoArtifactSystem.Unlock.cs, .XAT.cs и .cs. Числа — базовые настройки сборки, отдельные прототипы могут их менять.</p></details>
  <div class="science-tabs" role="group" aria-label="Справочник артефактов"><button data-science-mode="triggers" aria-pressed="true">Стимулы · что делать</button><button data-science-mode="effects" aria-pressed="false">Реакции · что произойдёт</button></div>
  <div class="science-controls"><label class="science-search"><span>Поиск по подсказке</span><input id="science-search" type="search" placeholder="Пульсирование, кровь, пена, телепортация…"></label><label><span>Раздел</span><select id="science-group"><option value="">Все разделы</option></select></label><label class="science-include"><input id="science-inactive" type="checkbox">Включая варианты вне стандартных таблиц</label></div>
  <div class="science-meta"><span id="science-count" role="status"></span><button id="science-reset" class="quiet">Сбросить фильтры</button></div><div id="science-results" class="science-results"></div>
  <details class="science-guide"><summary>Заметки исследователя</summary><label class="science-notes">ID артефакта, узлы и результаты опытов<textarea id="science-notes" placeholder="Артефакт… / узел… / стимул… / наблюдаемый эффект…"></textarea></label><p id="science-save" class="science-source">Заметки сохраняются в этом браузере отдельно от карточек рецептов.</p></details>
  <p class="science-source">Справочник по локальным прототипам сборки · данные собраны ${esc(data.generated)}. По умолчанию показаны варианты из стандартных таблиц. Названия совпадают с русскими подсказками игры; способы проверки и пояснения составлены по коду. Это справочник возможных эффектов, а не предсказание неизвестного узла.</p>`;
  function groups(){const values=[...new Set(data[mode].map(v=>v.group))];$('science-group').innerHTML='<option value="">Все разделы</option>'+values.map(v=>`<option>${esc(v)}</option>`).join('');}
  function render(){
    const words=$('science-search').value.toLowerCase().replaceAll('ё','е').trim().split(/\s+/).filter(Boolean),group=$('science-group').value;
    const all=data[mode],items=all.filter(v=>($('science-inactive').checked||v.active)&&(!group||v.group===group)&&words.every(word=>`${v.name} ${v.id} ${v.steps.join(' ')} ${(v.chemicals||[]).map(c=>c.name+' '+c.id).join(' ')} ${(v.spawned||[]).map(c=>c.name+' '+c.id).join(' ')}`.toLowerCase().replaceAll('ё','е').includes(word)));
    $('science-count').textContent=`Найдено: ${items.length} · в справочнике: ${all.length}`;
    $('science-results').innerHTML=items.map(v=>`<details class="science-card" data-science-id="${esc(v.id)}"><summary><span class="science-card-top"><span class="science-kind">${esc(v.group)}</span><span class="science-status ${v.active?'':'inactive'}">${esc(v.status)}</span></span><span class="science-name">${esc(v.name)}</span><span class="science-preview">${esc(v.steps[0])}</span><span class="science-more">${mode==='triggers'?'Как выполнить':'Что произойдёт'} <b>＋</b></span></summary><div class="science-card-body">${v.steps.length>1&&mode==='triggers'?'<p class="science-callout">Указанные способы срабатывания — альтернативы, если это не дополнительная подсказка осмотра.</p>':''}<ol>${v.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>${v.chemicals?.length?`<h4>Возможные реагенты</h4><div class="science-chips">${v.chemicals.map(c=>`<span title="${esc(c.id)}">${esc(c.name)}</span>`).join('')}</div>`:''}${v.spawned?.length?`<h4>Варианты создаваемых объектов</h4><ul class="science-spawns">${v.spawned.map(s=>`<li>${esc(s.name)} <code>${esc(s.id)}</code></li>`).join('')}</ul>`:''}<details class="source"><summary>Прототип и параметры</summary><p><code>${esc(v.source)} · ${esc(v.id)}</code></p><pre>${esc(JSON.stringify(v.raw,null,2))}</pre></details></div></details>`).join('')||'<div class="science-empty"><h3>Совпадений нет</h3><p>Попробуйте часть фразы из анализатора, другой раздел или включите варианты вне стандартных таблиц.</p></div>';
  }
  $('scientist').addEventListener('click',e=>{const b=e.target.closest('[data-science-mode]');if(!b)return;mode=b.dataset.scienceMode;document.querySelectorAll('[data-science-mode]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));groups();render();});
  for(const id of ['science-search','science-group','science-inactive'])$(id).addEventListener('input',render);
  $('science-reset').addEventListener('click',()=>{$('science-search').value='';$('science-group').value='';$('science-inactive').checked=false;render();});
  try{$('science-notes').value=localStorage.getItem('ss14-scientist-notes')||'';}catch{}
  $('science-notes').addEventListener('input',()=>{try{localStorage.setItem('ss14-scientist-notes',$('science-notes').value);$('science-save').textContent='Заметки сохранены в этом браузере.';}catch{$('science-save').textContent='Не удалось сохранить заметки. Скопируйте их перед закрытием страницы.';}});
  groups();render();
})();
