'use strict';
(() => {
  const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
  function safeEnergy(matter,mode=1){if(!Number.isFinite(matter)||matter<=0||![1,2,3].includes(mode))return NaN;const n=matter/32,k=[1,4,8][mode-1];return 800*k*n**1.5/(n+50/Math.sqrt(k));}
  function band(matter){return 3500*(matter/32>40?1:.2+.8*(matter/32)/40)*Math.sqrt(Math.log(2));}
  function shot(power,ratio){if(!Number.isFinite(power)||power<0||!Number.isFinite(ratio)||ratio<0||ratio>100)return null;return {matter:20*Math.sqrt(power*(1-ratio/100)/300),energy:80*Math.sqrt(power*ratio/100/300)};}
  function parseSamples(text){const lines=text.trim().split(/\r?\n/).filter(s=>s.trim());if(lines.length<2)throw Error('Нужны минимум два замера.');if(lines.length>500)throw Error('Не больше 500 строк за один расчёт.');const rows=lines.map((line,i)=>{const values=line.trim().split(';').map(s=>s.trim().replace(/\s/g,'').replace(',','.'));if(values.length!==3||values.some(s=>s===''))throw Error(`Строка ${i+1}: нужны время; материя; энергия.`);const [time,matter,energy]=values.map(Number);if(![time,matter,energy].every(Number.isFinite)||time<0||matter<=0||energy<0)throw Error(`Строка ${i+1}: некорректные числа.`);return {time,matter,energy};});for(let i=1;i<rows.length;i++)if(rows[i].time<=rows[i-1].time)throw Error('Время замеров должно строго возрастать.');return rows;}
  function slope(rows,key){const t0=rows[0].time,ts=rows.map(r=>r.time-t0),avgT=ts.reduce((s,v)=>s+v,0)/rows.length,avg=rows.reduce((s,r)=>s+r[key],0)/rows.length;return rows.reduce((s,r,i)=>s+(ts[i]-avgT)*(r[key]-avg),0)/ts.reduce((s,t)=>s+(t-avgT)**2,0);}
  function tune(rows,o){
    if(![o.target,o.horizon,o.window,o.gain,o.count,o.power,o.ratio].every(Number.isFinite)||o.target<=0||o.horizon<=0||o.window<=0||o.gain<=0||o.gain>1||!Number.isInteger(o.count)||o.count<1||o.count>32||!Number.isInteger(o.power)||o.power<600||o.power>16384||!Number.isInteger(o.ratio)||o.ratio<0||o.ratio>100||![1,2,3].includes(o.mode))throw Error('Проверьте настройки: мощность 600–16384, доля энергии 0–100%, целое число эмиттеров 1–32, положительные цель и интервалы.');
    if(o.hits!=null&&(!Number.isInteger(o.hits)||o.hits<0))throw Error('Число попаданий должно быть целым и неотрицательным.');
    const last=rows.at(-1),recent=rows.filter(r=>r.time>=last.time-o.window);if(recent.length<2)throw Error('В выбранном окне меньше двух замеров. Увеличьте окно.');
    const span=last.time-recent[0].time,rates={matter:slope(recent,'matter'),energy:slope(recent,'energy')},frequency=o.hits==null?4/13:o.hits/span/o.count;
    const oldShot=shot(o.power,o.ratio),old={matter:oldShot.matter*frequency*o.count,energy:oldShot.energy*frequency*o.count};
    const center=safeEnergy(last.matter,o.mode),desiredM=(o.target-last.matter)/o.horizon,delta=Math.max(.01,last.matter*.00001),derivative=(safeEnergy(last.matter+delta,o.mode)-safeEnergy(Math.max(.001,last.matter-delta),o.mode))/(2*delta),desiredE=(center-last.energy)/o.horizon+derivative*desiredM;
    const need={matter:old.matter+o.gain*(desiredM-rates.matter),energy:old.energy+o.gain*(desiredE-rates.energy)},notes=[];
    if(![...Object.values(need),...Object.values(rates),center,safeEnergy(o.target,o.mode)].every(Number.isFinite))throw Error('Масштаб чисел слишком велик для расчёта. Проверьте замеры и интервалы.');
    if(span<30)notes.push('Короткий замер: соберите хотя бы 30–60 секунд при неизменных настройках.');
    if(recent.length<3)notes.push('Две точки дают только средний наклон; добавьте промежуточные замеры для оценки дрейфа.');
    if(o.hits==null)notes.push('Темп попаданий оценён по среднему циклу 4/13 выстрела в секунду на эмиттер. Реальные паузы случайны; лучше посчитать попадания за выбранное окно.');
    if(recent.length>=4){const mid=Math.floor(recent.length/2),early=recent.slice(0,mid),late=recent.slice(mid);if(['matter','energy'].some(k=>Math.abs(slope(late,k)-slope(early,k))>Math.max(.5,Math.abs(rates[k])*.25)))notes.push('Скорость заметно меняется внутри окна: среда дрейфует. Старый баланс устаревает; уменьшите шаг коррекции и повторите замер.');}
    if(Math.abs(last.energy-center)>band(last.matter))notes.push('Текущая энергия вне полосы выбранного режима. Калькулятор не рассчитывает безопасный переход между режимами; контролируйте целостность и охлаждение.');
    if(need.matter<0||need.energy<0)notes.push('Требуется отрицательная добавка по одному из каналов. Эмиттер не отнимает материю или энергию: одного изменения его настроек недостаточно.');
    if(frequency===0)return {recent,rates,center,finalEnergy:safeEnergy(o.target,o.mode),notes:[...notes,'За окно нет попаданий. Проверьте питание и попадание лучей; расчёт новой мощности невозможен.'],recommendation:null};
    if(need.matter<=0&&need.energy<=0)return {recent,rates,center,finalEnergy:safeEnergy(o.target,o.mode),notes:[...notes,'По обоим каналам дополнительная подача не требуется. Рассмотрите отключение этой группы и новый замер; эмиттеры не могут обеспечить отрицательный поток.'],recommendation:null};
    const per=frequency*o.count,m=Math.max(0,need.matter)/(20*per),e=Math.max(0,need.energy)/(80*per),idealPower=300*(m*m+e*e),ratio=idealPower?Math.round(100*e*e/(m*m+e*e)):0,power=Math.round(clamp(idealPower,600,16384)),next=shot(power,ratio);
    if(!Number.isFinite(idealPower)||!next)throw Error('Расчёт выходит за числовой диапазон. Проверьте замеры и число попаданий.');
    if(idealPower<600)notes.push('Запрос ниже минимальных 600 Вт на эмиттер. Показан минимум, который не обеспечит точный баланс; уменьшите число работающих эмиттеров и сделайте новый замер.');
    if(idealPower>16384)notes.push('Запрос выше максимальных 16384 Вт на эмиттер. Показан предел; удержание цели этой группой не обеспечивается.');
    const predicted={matter:rates.matter+next.matter*per-old.matter,energy:rates.energy+next.energy*per-old.energy};
    return {recent,rates,center,finalEnergy:safeEnergy(o.target,o.mode),notes,need,old,idealPower,predicted,recommendation:{power,ratio,matterRatio:100-ratio,count:o.count}};
  }
  const api={safeEnergy,band,shot,parseSamples,slope,tune};if(typeof module!=='undefined')module.exports=api;if(typeof window==='undefined')return;window.SupermatterDesk=api;
  const host=document.getElementById('atmos-sm');if(!host)return;const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(n),esc=s=>String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const field=(name,label,value,min,max,step='any')=>`<label>${label}<input name="${name}" type="number" value="${value}" min="${min}" ${max==null?'':`max="${max}"`} step="${step}" required></label>`;
  host.innerHTML=`<div class="atmos-panel"><h3>СМ: удержание материи и энергии</h3><p>Цель по умолчанию — <b>100 000 материи</b>. Одного числа материи недостаточно: энергия должна следовать выбранной полосе устойчивости, а подача — компенсировать текущий обмен с газами.</p><p class="science-source">Помощник работает по вашим замерам, не подключается к игре и не управляет эмиттерами. Он оценивает следующий шаг подстройки при сохранении условий, а не обещает бесконечно стабильную настройку.</p></div><form id="sm-form" class="atmos-panel"><h3>1. Цель и действующие эмиттеры</h3><div class="anomaly-helper-grid">${field('target','Цель: материя',100000,.001)}<label>Полоса энергии<select name="mode"><option value="1">Режим 1</option><option value="2">Режим 2</option><option value="3">Режим 3</option></select></label>${field('count','Работающих эмиттеров с одинаковыми настройками',1,1,32,1)}${field('power','Сейчас: мощность каждого, Вт',600,600,16384,1)}${field('ratio','Сейчас: доля энергии, % (остальное — материя)',50,0,100,1)}${field('horizon','Плавный возврат к цели за, с',300,1)}${field('window','Использовать последние, с',60,1)}${field('gain','Доля рассчитанной поправки (0–1)',.5,.01,1,.01)}<label>Всего попаданий за выбранное окно, шт.<input name="hits" type="number" min="0" step="1" placeholder="Не считали — средний темп"></label></div><h3>2. Замеры при этих настройках</h3><p class="science-source">Одна строка: <b>время в секундах; материя; внутренняя энергия</b>. Переписывайте абсолютные значения с наблюдателя. Десятичная запятая разрешена; 100 тысяч пишите «100000» или «100 000». Соберите несколько точек за 30–60 секунд без смены газа, мощности и числа эмиттеров. При ручном вводе используйте время показания, а не момент вставки текста.</p><label class="sm-samples-label">История текущего режима<textarea name="samples" id="sm-samples" rows="7" placeholder="0; 100000; 44000&#10;30; 99900; 43900&#10;60; 99800; 43800" required spellcheck="false"></textarea></label><div class="botany-buttons"><button type="submit" class="secondary">Рассчитать поправку</button><button type="button" id="sm-new-window" class="quiet">Новый замер после изменения настроек</button></div><p id="sm-stale" class="science-callout" role="status"></p><div id="sm-result" aria-live="polite"></div></form>
  <details class="science-guide"><summary>Почему без подстройки накапливается отклонение</summary><div class="science-card-body"><p>Распад материи зависит от температуры, давления и газов; часть газа синтезируется в материю. Энергия обменивается с газом и уходит в излучение и разряды. Даже при неизменной мощности эмиттеров меняется компенсация потерь. Постоянная небольшая ошибка скорости со временем даёт большое отклонение количества.</p><p>По умолчанию сервер рассылает показания раз в 1 секунду (настройка сервера может отличаться). Показанные производные усредняются по атмосферным обновлениям; добавки от отдельных попаданий происходят вне этого участка расчёта. Поэтому здесь наклон считается из абсолютных значений за окно, включая попадания.</p><p>У стандартного эмиттера в этой реализации цикл содержит четыре выстрела с тремя промежутками по 2 с, затем случайную паузу 4–10 с: в среднем 4/13 попадания в секунду при попадании всех лучей. Начальный запуск ждёт 10 с. Короткий замер может попасть на паузу или очередь.</p><ol><li>Сначала стабилизируйте газовый контур и охладитель. Используйте реальные показания СМ, не температуру соседней трубы.</li><li>Снимите несколько абсолютных показаний и посчитайте попадания, если возможно.</li><li>Получите поправку и вручную установите её в игре. При изменении настроек начните новую историю; не смешивайте замеры разных режимов.</li><li>Дождитесь нескольких очередей и обновлений наблюдателя. Повторите расчёт; если скорость меняется внутри окна, уменьшите долю поправки.</li><li>После приближения к 100 000 продолжайте контроль: постоянной настройки, независимой от состояния среды, этот расчёт не предполагает.</li></ol></div></details>
  <details class="source"><summary>Формулы и источники</summary><p>На попадание: ΔM = 20√(P(1−r)/300), ΔE = 80√(Pr/300), где r — доля энергии. Центр полосы: E = 800k·n^1,5 / (n + 50/√k), n = M/32, k = 1, 4 или 8. Это внутренняя энергия СМ, не электрическая мощность станции.</p><p>Расчёт компенсирует измеренный наклон с плавным возвратом к цели. При движении материи целевая энергия следует текущему центру выбранной полосы. Округление до целой мощности и процента, ограничения эмиттера и будущие изменения газа создают остаточную ошибку.</p><code>Content.Shared/SS220/SuperMatter/Functions/SuperMatterFunctions.cs<br>Content.Shared/SS220/SuperMatter/Emitter/SharedSuperMatterEmitterExtensionConsts.cs<br>Content.Server/SS220/SuperMatter/Emitter/SuperMatterEmitterExtensionSystem.cs<br>Content.Server/SS220/SuperMatter/Crystal/SuperMatterSystem.Thermodynamics.cs<br>Content.Server/SS220/SuperMatter/Crystal/SuperMatterSystem.Database.cs<br>Content.Server/Singularity/EntitySystems/EmitterSystem.cs</code></details>`;
  function graph(rows,key,target,title){let lo=Math.min(target,...rows.map(r=>r[key])),hi=Math.max(target,...rows.map(r=>r[key]));const pad=Math.max(1,(hi-lo)*.1);lo-=pad;hi+=pad;const t0=rows[0].time,span=rows.at(-1).time-t0,x=t=>65+(t-t0)/span*490,y=v=>145-(v-lo)/(hi-lo)*115,points=rows.map(r=>`${x(r.time)},${y(r[key])}`).join(' ');return `<figure class="sm-plot"><figcaption>${title}: ${fmt(rows[0][key])} → ${fmt(rows.at(-1)[key])}</figcaption><svg viewBox="0 0 580 185" role="img" aria-label="${title}: фактические замеры, пунктир — ориентир"><text x="3" y="22">${fmt(hi)}</text><text x="3" y="157">${fmt(lo)}</text><line x1="65" x2="555" y1="${y(target)}" y2="${y(target)}" stroke="#c8ab70" stroke-dasharray="5 5"/><polyline points="${points}" fill="none" stroke="#a8d98e" stroke-width="2"/>${rows.map(r=>`<circle cx="${x(r.time)}" cy="${y(r[key])}" r="3" fill="#a8d98e"/>`).join('')}<text x="65" y="178">${fmt(t0)} с</text><text x="490" y="178">${fmt(rows.at(-1).time)} с</text></svg><small>Ориентир: ${fmt(target)}. Линия соединяет введённые замеры; это не живая телеметрия.</small></figure>`;}
  const form=$('sm-form');
  const thumbnail=window.AtmosThumbnail||(()=> '');
  host.querySelector('h3').insertAdjacentHTML('afterbegin',thumbnail('sm')+' ');
  form.querySelector('h3').insertAdjacentHTML('afterbegin',thumbnail('emitter')+' ');
  form.querySelector('.anomaly-helper-grid').insertAdjacentHTML('afterend','<p id="sm-targets" class="science-source"></p>');
  function targets(){const m=Number(form.elements.target.value);$('sm-targets').textContent=m>0&&Number.isFinite(m)?`Центры энергии при ${fmt(m)} материи: ${[1,2,3].map(k=>`режим ${k} — ${fmt(safeEnergy(m,k))}`).join(' · ')}. Выберите уже используемый режим; это не инструкция переключения между полосами.`:'Введите положительную цель по материи.';}
  targets();form.elements.target.addEventListener('input',targets);
  form.addEventListener('submit',e=>{e.preventDefault();try{const options=Object.fromEntries(['target','mode','count','power','ratio','horizon','window','gain'].map(k=>[k,form.elements[k].value.trim()===''?NaN:Number(form.elements[k].value)]));options.hits=form.elements.hits.value===''?null:Number(form.elements.hits.value);const r=tune(parseSamples(form.elements.samples.value),options),last=r.recent.at(-1);$('sm-stale').textContent='';$('sm-result').innerHTML=`<h3>Среднее изменение: материя ${fmt(r.rates.matter)}/с · энергия ${fmt(r.rates.energy)}/с</h3><p>Сейчас центр режима ${options.mode}: <b>${fmt(r.center)}</b> энергии. При цели ${fmt(options.target)} материи: <b>${fmt(r.finalEnergy)}</b>. Полуширина полосы без повреждения от соотношения M/E сейчас: ±${fmt(band(last.matter))}; это не оценка общей безопасности установки.</p>${r.recommendation?`<div class="sm-recommendation"><b>Следующая пробная настройка каждого из ${r.recommendation.count}: ${r.recommendation.power} Вт</b><p>Энергия ${r.recommendation.ratio}% · материя ${r.recommendation.matterRatio}%.</p><p>При прежних условиях ожидаемый наклон после поправки: материя ${fmt(r.predicted.matter)}/с, энергия ${fmt(r.predicted.energy)}/с. Частичная поправка намеренно может оставить отклонение.</p></div>`:''}${r.notes.length?`<ul class="science-callout">${r.notes.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`:''}<div class="sm-plots">${graph(r.recent,'matter',options.target,'Материя')}${graph(r.recent,'energy',r.center,'Внутренняя энергия')}</div>`;}catch(error){$('sm-result').textContent=error.message;}});
  form.addEventListener('input',()=>{if($('sm-result').textContent){$('sm-result').replaceChildren();$('sm-stale').textContent='Данные изменились — рассчитайте поправку заново. При смене настроек в игре начните новое окно замеров.';}});
  $('sm-new-window').addEventListener('click',()=>{form.elements.samples.value='';form.elements.hits.value='';$('sm-result').replaceChildren();$('sm-stale').textContent='История очищена. Введите действующие настройки и новые замеры после их применения.';form.elements.samples.focus();});
})();
